// Generated by https://quicktype.io

export interface Notification {
    action:       Action;
    notification: OSNotificacion;
}



export interface Action {
    type: number;
}


export interface CustomData {
    a: Record<string, unknown>;
    i: string;
  }
  
  export interface RawPayload {
    'google.delivered_priority': string;
    'google.sent_time': number;
    'google.ttl': number;
    'google.original_priority': string;
    custom: string;
    pri: string;
    vis: string;
    from: string;
    alert: string;
    title: string;
    'google.message_id': string;
    'google.c.sender.id': string;
    androidNotificationId: number;
  }
  
  export interface NestedObject {
    nestedProperty1: string;
    nestedProperty2: string;
    nestedProperty3: {
      nestedProperty4: string;
      nestedProperty5: string;
    };
  }
  
  export interface OSNotificacion {
    androidNotificationId: number;
    groupedNotifications: unknown[];
    notificationId: string;
    templateName: string;
    templateId: string;
    title: string;
    body: string;
    lockScreenVisibility: number | undefined;
    fromProjectNumber: string;
    priority: number;
    additionalData: Record<string, unknown>;
    rawPayload: RawPayload;
    someNestedObject: NestedObject;
  }

  


